server:
  port: 8090
  max-http-header-size: 102400

web:
#  upload-path: /webserver/upload
  upload-path: upload/

spring:

  resources:
    static-locations: file:${web.upload-path}

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/group_purchasing?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: rfV@2020$
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


member:
  price: 10

#  thymeleaf:
#    check-template: false
#    check-template-location: false
#    prefix: classpath:/templates/    # 文件目录
#    suffix: .html   # 模板后缀
#    mode: HTML
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#    cache: false
#  mvc:
#    view:
#      prefix: /WEB-INF/
#      suffix: .html

#  devtools:
#    restart:
#      enabled: true

#  servlet:
#    multipart:
#      max-file-size: 50MB
#      max-request-size: 50MB



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.share.GroupPurchasing.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




weixinpay:
  mchId: 1536086381
  storePassword: pcH5Rj986nlegasgN17DibrGhhU8y17pMnpppdaff
  appid: wx7cd99cd97afdafd8523b6
  secretKey: 55fbe41821276asadfasf0f82c5dd2gdrfg30291707f
  notifyUrl: https:
  keystore: /Users/xingjw/Code/IdeaProjects/webserver/static/cert/apiclient_cert.p12
  unifiedorderUrl: https://api.mch.weixin.qq.com/pay/unifiedorder
  refundorderUrl: https://api.mch.weixin.qq.com/secapi/pay/refund





logback:
  log_home: log/


#static_path: /Users/xingjw/Code/IdeaProjects/webserver/static

#beetl:
#  pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql


#cookie:
#  cookie_name: pilates_user
#  cookie_exp: 604800





#JWT
# 签发者
#jwt:
#  issuer: Augmentum
#  header: Authorization
#  # 过期时间（-1永不过期）
#  expires_in: -1
#  #jwt.expires_in=86400
#  # 密匙
#  secret: gvdlju
#  cookie: AUTH-TOKEN






